"https://{default}/":
  type: upstream
  upstream: "app:http"
  redirects:
    paths:
      '/check-api':
        to: 'https://fivetran.com/check-api'
        code: 307
        
"https://{default}/hello-world":
  type: upstream
  upstream: "varnish:http"
  cache:
      enabled: false
